apiVersion: v1
kind: Pod
metadata:
  name: examine-ephemeral-volume-pod
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: nginx
      volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
  volumes:
    - name: tmp-volume
      emptyDir: {}
